Repository GeoStat-Framework/GSTools, pull requests merged in 2020-12, with the labels that each got.

#116 Fix some typos in the new examples
  examples/01_random_field/05_mesh_ensemble.py
  examples/01_random_field/06_higher_dimensions.py
Labels: Documentation

#117 minor CI fixes
  .github/workflows/main.yml
Labels: CI/CD

#122 Cubic covariance model
  examples/02_cov_model/README.rst
  gstools/__init__.py
  gstools/covmodel/__init__.py
  gstools/covmodel/models.py
  tests/test_covmodel.py
Labels: enhancement

#59 Add PyVista mesh support to Field
  gstools/field/base.py
  tests/test_srf.py
Labels: enhancement
