Repository GeoStat-Framework/GSTools, pull requests merged in 2020-11, with the labels that each got.

#87 Implemented directional variograms for `unstructured`
  gstools/variogram/estimator.pyx
  gstools/variogram/variogram.py
  tests/test_variogram_unstructured.py
Labels: enhancement

#107 CI update: provide Python 3.9 wheels
  .travis.yml
  gstools/covmodel/base.py
  gstools/krige/base.py
  setup.py
Labels: CI/CD, enhancement

#108 CovModel: sort opt_arg
  gstools/covmodel/base.py
Labels: enhancement

#109 CovModel: Update and Refactoring
  docs/source/conf.py
  examples/00_misc/README.rst
  examples/01_random_field/README.rst
  examples/02_cov_model/README.rst
  examples/03_variogram/04_directional_2d.py
  examples/03_variogram/05_directional_3d.py
  examples/03_variogram/README.rst
  examples/04_vector_field/README.rst
  examples/05_kriging/README.rst
  examples/06_conditioned_fields/README.rst
  examples/07_transformations/README.rst
  gstools/__init__.py
  gstools/covmodel/__init__.py
  gstools/covmodel/base.py
  gstools/covmodel/fit.py
  gstools/covmodel/models.py
  gstools/covmodel/plot.py
  gstools/covmodel/tools.py
  gstools/covmodel/tpl_models.py
  gstools/field/base.py
  gstools/field/generator.py
  gstools/field/srf.py
  gstools/field/tools.py
  gstools/krige/base.py
  gstools/krige/methods.py
  gstools/random/rng.py
  gstools/random/tools.py
  gstools/tools/__init__.py
  gstools/tools/geometric.py
  gstools/tools/misc.py
  gstools/variogram/variogram.py
  tests/test_covmodel.py
  tests/test_variogram_unstructured.py
Labels: Refactoring, enhancement

#111 CovModel.fit: check if weights are given as a string to prevent numpy comparison errors in the future
  gstools/covmodel/fit.py
Labels: bug

#112 [Field] refactoring and update
  docs/requirements_doc.txt
  examples/01_random_field/05_mesh_ensemble.py
  examples/01_random_field/06_higher_dimensions.py
  examples/03_variogram/00_fit_variogram.py
  examples/03_variogram/02_find_best_model.py
  examples/03_variogram/04_directional_2d.py
  examples/03_variogram/05_directional_3d.py
  gstools/__init__.py
  gstools/covmodel/plot.py
  gstools/field/base.py
  gstools/field/condition.py
  gstools/field/generator.py
  gstools/field/plot.py
  gstools/field/srf.py
  gstools/field/summator.pyx
  gstools/field/tools.py
  gstools/krige/base.py
  gstools/krige/tools.py
  gstools/tools/__init__.py
  gstools/tools/export.py
  gstools/tools/geometric.py
  gstools/variogram/variogram.py
  requirements.txt
  tests/test_incomprrandmeth.py
  tests/test_krige.py
  tests/test_randmeth.py
  tests/test_srf.py
Labels: Refactoring, enhancement

#114 Migrate from TravisCI to GitHub Actions
  .github/workflows/main.yml
  .travis.yml
  README.md
  requirements_setup.txt
Labels: CI/CD, organization
