Repository GeoStat-Framework/GSTools, pull requests merged in 2021-01, with the labels that each got.

#125 CI: The sdists should only be uploaded once to the artifact
  .github/workflows/main.yml
Labels: CI/CD, bug

#129 Coveralls 3.0 bugfix
  .github/workflows/main.yml
Labels: CI/CD

#113 Add support for geographical coordinates
  README.md
  docs/source/conf.py
  docs/source/index.rst
  docs/source/tutorials.rst
  examples/00_misc/03_precipitation.py
  examples/00_misc/README.rst
  examples/01_random_field/04_srf_merge.py
  examples/01_random_field/README.rst
  examples/01_random_field/mesh_ensemble.vtk
  examples/02_cov_model/README.rst
  examples/03_variogram/README.rst
  examples/04_vector_field/README.rst
  examples/05_kriging/README.rst
  examples/06_conditioned_fields/README.rst
  examples/07_transformations/README.rst
  examples/08_geo_coordinates/00_field_generation.py
  examples/08_geo_coordinates/01_dwd_krige.py
  examples/08_geo_coordinates/README.rst
  examples/08_geo_coordinates/de_borders.txt
  examples/08_geo_coordinates/temp_obs.txt
  gstools/__init__.py
  gstools/covmodel/base.py
  gstools/covmodel/fit.py
  gstools/covmodel/plot.py
  gstools/covmodel/tools.py
  gstools/field/base.py
  gstools/field/generator.py
  gstools/field/plot.py
  gstools/field/srf.py
  gstools/krige/base.py
  gstools/tools/__init__.py
  gstools/tools/export.py
  gstools/tools/geometric.py
  gstools/variogram/estimator.pyx
  gstools/variogram/variogram.py
  tests/test_incomprrandmeth.py
  tests/test_latlon.py
  tests/test_randmeth.py
  tests/test_srf.py
Labels: Documentation, Refactoring, enhancement

#133 README: badges from develop
  README.md
Labels: Documentation, organization

#132 Examples: add PyVista/VTK example
  .gitignore
  docs/source/conf.py
  docs/source/pics/GS_pyvista_cut.png
  docs/source/pics/paraview.png
  examples/00_misc/01_export.py
  examples/01_random_field/06_pyvista_support.py
  examples/01_random_field/07_higher_dimensions.py
  examples/01_random_field/mesh_ensemble.vtk
  examples/08_geo_coordinates/README.rst
Labels: Documentation

#130 New Class for Conditioned Spatial Random Fields
  examples/05_kriging/05_universal_kriging.py
  examples/06_conditioned_fields/00_condition_ensemble.py
  examples/08_geo_coordinates/01_dwd_krige.py
  gstools/__init__.py
  gstools/covmodel/base.py
  gstools/covmodel/plot.py
  gstools/field/__init__.py
  gstools/field/base.py
  gstools/field/cond_srf.py
  gstools/field/condition.py
  gstools/field/generator.py
  gstools/field/srf.py
  gstools/krige/base.py
  gstools/krige/krigesum.pyx
  gstools/random/rng.py
  gstools/random/tools.py
  tests/test_condition.py
  tests/test_latlon.py
Labels: Performance, Refactoring, enhancement

#136 Examples: update dwd example to use wetterdienst 0.13
  examples/08_geo_coordinates/01_dwd_krige.py
Labels: Documentation
