Repository GeoStat-Framework/GSTools, pull requests merged in 2022-08, with the labels that each got.

#247 Remove deprecated scipy method pinv2
  src/gstools/krige/base.py
  src/gstools/krige/methods.py
Labels: bug

#254 pykrige: fix passed variogram in case of geo-coord
  src/gstools/covmodel/base.py
Labels: bug, enhancement, external problem

#257 refactor(src): readability improvements
  src/gstools/covmodel/base.py
  src/gstools/covmodel/fit.py
  src/gstools/covmodel/models.py
  src/gstools/covmodel/plot.py
  src/gstools/covmodel/tools.py
  src/gstools/field/base.py
  src/gstools/field/cond_srf.py
  src/gstools/field/generator.py
  src/gstools/field/srf.py
  src/gstools/field/tools.py
  src/gstools/field/upscaling.py
  src/gstools/krige/base.py
  src/gstools/krige/methods.py
  src/gstools/normalizer/base.py
  src/gstools/normalizer/tools.py
  src/gstools/random/tools.py
  src/gstools/tools/misc.py
  src/gstools/tools/special.py
  src/gstools/transform/array.py
  src/gstools/transform/field.py
  src/gstools/variogram/variogram.py
Labels: Documentation

#250 Add better support for custom generators
  pyproject.toml
  src/gstools/field/base.py
  src/gstools/field/cond_srf.py
  src/gstools/field/generator.py
  src/gstools/field/srf.py
  src/gstools/krige/base.py
Labels: enhancement

#259 Generator: add abstract __init__
  src/gstools/field/generator.py
Labels: enhancement

#255 Cherry picks minor fixes for v1.4
  src/gstools/__init__.py
  src/gstools/covmodel/base.py
  src/gstools/variogram/estimator.pyx
  tests/test_covmodel.py
Labels: enhancement

#261 prepare v1.4 release
  .github/workflows/main.yml
  CHANGELOG.md
  docs/source/conf.py
  pyproject.toml
Labels: Documentation
