Repository GeoStat-Framework/GSTools, pull requests merged in 2024-07, with the labels that each got.

#354 Drop deprecated conditional compilation
  README.md
  docs/source/index.rst
  src/gstools/config.py
  src/gstools/field/generator.py
  src/gstools/field/summator.pyx
  src/gstools/krige/base.py
  src/gstools/krige/krigesum.pyx
  src/gstools/variogram/estimator.pyx
  src/gstools/variogram/variogram.py
Labels: bug

#302 Add a Fourier generator for periodic spatial random fields
  .github/workflows/main.yml
  README.md
  docs/source/index.rst
  examples/01_random_field/08_fourier.py
  examples/01_random_field/09_fourier_trans.py
  examples/01_random_field/README.rst
  src/gstools/field/generator.py
  src/gstools/field/srf.py
  src/gstools/field/summator.pyx
  tests/test_fouriergen.py
Labels: enhancement, help wanted

#356 replace deprecated license identifier
  .zenodo.json
Labels: bug, external problem

#359 Fix coveralls
  .github/workflows/main.yml
  src/gstools/field/summator.pyx
Labels: bug, CI/CD
