Repository GeoStat-Framework/GSTools, pull requests merged in 2025-04, with the labels that each got.

#370 Plurigaussian fields
  README.md
  docs/source/conf.py
  docs/source/index.rst
  docs/source/pics/2d_pgs.png
  docs/source/pics/3d_pgs.png
  docs/source/tutorials.rst
  examples/00_misc/01_export.py
  examples/01_random_field/06_pyvista_support.py
  examples/04_vector_field/01_3d_vector_field.py
  examples/11_plurigaussian/00_simple.py
  examples/11_plurigaussian/01_pgs.py
  examples/11_plurigaussian/02_spatial_relations.py
  examples/11_plurigaussian/03_correlations.py
  examples/11_plurigaussian/04_3d_pgs.py
  examples/11_plurigaussian/05_conditioned.py
  examples/11_plurigaussian/06_periodic.py
  examples/11_plurigaussian/README.rst
  examples/11_plurigaussian/conditional_values.npz
  src/gstools/__init__.py
  src/gstools/field/__init__.py
  src/gstools/field/generator.py
  src/gstools/field/pgs.py
  tests/test_pgs.py
Labels: enhancement, help wanted

#364 Add sum model
  MANIFEST.in
  docs/source/conf.py
  docs/source/tutorials.rst
  examples/12_sum_model/00_simple_sum_model.py
  examples/12_sum_model/01_fitting_sum_model.py
  examples/12_sum_model/README.rst
  pyproject.toml
  src/gstools/__init__.py
  src/gstools/covmodel/__init__.py
  src/gstools/covmodel/base.py
  src/gstools/covmodel/fit.py
  src/gstools/covmodel/models.py
  src/gstools/covmodel/plot.py
  src/gstools/covmodel/sum_tools.py
  src/gstools/covmodel/tools.py
  src/gstools/covmodel/tpl_models.py
  src/gstools/field/generator.py
  tests/data/variogram.txt
  tests/test_covmodel.py
  tests/test_sum_model.py
Labels: enhancement, Refactoring

#376 Outsource Cython backend
  .github/workflows/main.yml
  MANIFEST.in
  docs/source/index.rst
  pyproject.toml
  setup.py
  src/gstools/field/generator.py
  src/gstools/field/summator.pyx
  src/gstools/krige/base.py
  src/gstools/krige/krigesum.pyx
  src/gstools/variogram/estimator.pyx
  src/gstools/variogram/variogram.py
Labels: enhancement, Refactoring, CI/CD, dependencies

#383 Prepare v1.7
  CHANGELOG.md
  README.md
  docs/source/index.rst
Labels: Documentation
